### PR TITLE
Improve English flow in README.md and related files

### PR DESCRIPTION
**Pull request by davidhutchens**
This is the PR improving the English in README.md and docs/ as promised in #764.

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
Can you please make linter happy?

**Comment by davidhutchens** [comment]
I closed this because there are several lines that exceed the 130 characters check. I'll fix them and do a new PR.

**Comment by maehne** [comment]
@davidhutchens: Next time, you can simply commit your additional fixes and push them to the branch of the existing pull request. It's is very common than PRs evolve over time before they get merged.

**Comment by MarcinOrlowski** [comment]
@davidhutchens you can also mark your PR `Draft` and keep working on it. When you done, you mark it "ready for review"

ss

**Pull request closed without merging**
