### PR TITLE
Bump colorpicker to 1.4.2

### PR DESCRIPTION
**Pull request by dheid**
Hi @BFH-ktt1,

there is a new colorpicker version out there. Nothing special, but newer. :-)

Best regards

Daniel

### CODE REVIEW

**Review by maehne — APPROVED** [review]
Looks good to me, but is already superseded by PR #1520, which updates colorpicker to 1.4.3. So, make sure that this one gets merged first or not at all!

**Comment by davidhutchens** [comment]
Good catch, @maehne. It is probably better to not merge this PR at all, since merging this and then #1520 will likely cause a merge conflict for no good reason.

**Comment by dheid** [comment]
1.4.2 has a bug, so let's skip this PR and use 1.4.3 directly

**Comment by BFH-ktt1** [comment]
Closing this one due to PR #1520

**Pull request closed without merging**
