### PR TITLE
Add Clear pixel dot feature on RGB Video Component

### PR DESCRIPTION
**Pull request by RomaricKc1**
New ```IO Pin``` added called ```CLR``` for clear that clears a pixel dot that has been previously written using ```WE``` and a color.

The ```CLR``` is ``` 1-bit wide 0 or 1```, asynchronous, it does react, whether the clock is ticking or not.
Can ```clear``` a pixel dot at a specific ```(x, y)```coordinate.

To clear all the pixels, use the previous ```RST``` pin. Instead of darkening the entire display, it turns it into the original state ```Yellow``` color. Original when you first place the component or when you hit ```Ctrl+R```.

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@RomaricKc1 : Thanks for this PR, could you please resolve the conflict?

**Comment by R3dst0ne** [comment]
In my opinion, we as a group should discuss how the RGB Video Component should work before thinking about merging this PR.

IMO, the way the component works is good and should not be changed.

Instead of resetting an individual pixel, it is common to simply draw over it with the default color (black).

The display is initially yellow because the state of each pixel is not known.
So resetting the simulation should set it to yellow, but an IO reset should set each pixel to the default color (black).
To make this more clear, it might be worth it to change from yellow to the unknown state color (set in preferences, default: blue).

**Comment by RomaricKc1** [comment]
> In my opinion, we as a group should discuss how the RGB Video Component should work before thinking about merging this PR.
> 
> IMO, the way the component works is good and should not be changed.
> 
> Instead of resetting an individual pixel, it is common to simply draw over it with the default color (black).
> 
> The display is initially yellow because the state of each pixel is not known. So resetting the simulation should set it to yellow, but an IO reset should set each pixel to the default color (black). To make this more clear, it might be worth it to change from yellow to the unknown state color (set in preferences, default: blue).
> 
> And of course adding documentation to explain this behavior would be great.

Yes, you are right, it should not be done by an individual.

I thought that the old ```RST``` was not working because the screen at default state is dark, that this dark color should be set using a color code say ```0000``` for ```monochrome 4-bit```. 

As of now resetting the simulation does not set it to the unknown yellow state. In my modifications, the RST does work this way so does the CLR input but for one pixel.

**Comment by RomaricKc1** [comment]
@R3dst0ne I think I understand now what you meant. That was my fault for not understanding the component. My post in ```issues``` #1524  I thought the display is yellow at the default state.

Instead of using a separate ```CLR``` pin, the display may be initialized with the ```black``` color and the user chose the desired color code to write to a pixel. Or better, keep things as they are, the user first ```needs``` to ```reset``` the display so everything turns ```black```, and use the color code desired for each pixel. This way, only the used pixel is colored. The rest of them is black.

In all cases, to remove a dot, (what I thought would require an additional ctrl pin) will be simply to write to a pixel the code ```0000``` for monochrome 4-bit (the one I use regularly) with the display previously reset.

**Comment by BFH-ktt1** [comment]
Closing PR as resolved, please reopen if I understood something wrong

**Pull request closed without merging**
