### PR TITLE
scroll workaround for #1368

### PR DESCRIPTION
**Pull request by dbh201**
* #1368

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
Can you please zoom based on current mouse coords? Because otherwise this PR is not really a fix.

**Comment by dbh201** [comment]
Yeah, that's just a quick fix I had done locally. I'm going to take a closer look today.

**Comment by MarcinOrlowski** [comment]
Thanks @dbh201  In meantime please turn this PR into "Draft" so we know it is work in progress.

**Comment by dbh201** [comment]
I'd say it's working now.

**Review by maehne — APPROVED** [review]
Looks good to me! Thanks @dbh201!

**Pull request merged**
