### PR TITLE
Update of the buffer.html not.html index.html library documents to version 3.5

### PR DESCRIPTION
**Pull request by mbaillif**

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
@davidhutchens can you please be a reviewer of this PR?

**Comment by davidhutchens** [comment]
I don't have an ability to self-assign as a reviewer; but I did look over the PR. I cannot review the non-English changes.

I have only one minor suggestion. In src/main/resources/doc/en/html/libs/wiring/probe.html, line 92, this removes the comma after "being added,". I would leave that comma in.

Otherwise, this looks good to me.

**Comment by mbaillif** [comment]
Thank you,
I added  "," line 92

**Review by davidhutchens — APPROVED** [review]
As I said above, this looks good to me. Thank you, @mbaillif, for updating and cleaning up the documentation.

**Pull request merged**
