### PR TITLE
Refactor Startup, TTY and GUI

### PR DESCRIPTION
**Pull request by dtowell**
This is a draft of significant changes to startup with a goal of completely separating TTY mode from GUI mode. There are separate classes, and Startup only handles argument/options processing (mostly). Additionally, the return code for most operations have been standardized to be 0=no error, 1=arg error, 2=file error; except for test options, which still return the previous values.

Tests have been created for some of the code, I expect to add more but I may need some help with mocking--the existing architecture makes mocking very difficult.

Documentation has not been updated, I expect to work on that, but wanted feedback before committing to it.

As far as I know, I have not changed the meaning of any options, however, some combinations which I determined to be meaningless have been prevented, and some that were misleading are reported. There is some work left to do here. Possibly some discussions about what SHOULD be allowed.

### CODE REVIEW

**Comment by dtowell** [comment]
This is just a draft/preview. I'll fix the lint/style issues.

**Comment by BFH-ktt1** [comment]
@dtowell : Thanks a lot for the work, it looks good to me

**Review by maehne — COMMENTED** [review]
Thanks @dtowell for your refactoring effort! For me it goes in the right direction!

**Comment by maehne** [comment]
@dtowell: Why did you close this PR? If you just need to resolve some conflicts with `develop` or need to revert some conflicting commits, you could do so in this PR. You could even squash and force push if need be.

**Comment by dtowell** [comment]
> @dtowell: Why did you close this PR? If you just need to resolve some conflicts with `develop` or need to revert some conflicting commits, you could do so in this PR. You could even squash and force push if need be.

Clearly I don't know how to use these tools (yet). I only posted the PR to get some feedback before continuing work. I was/am getting messages about things not building and I didn't want the code to bother anyone or even be noticed yet as it is still in progress. If you could point me to a resource that explains typical workflows I would be happy to learn. I use VSCode but interact with github via the web, if that matters.

**Comment by MarcinOrlowski** [comment]
> If you could point me to a resource that explains typical workflows

@dtowell Please elaborate what precisely you need assistance with?

**Comment by dtowell** [comment]
> > If you could point me to a resource that explains typical workflows
> 
> @dtowell Please elaborate what precisely you need assistance with?

@MarcinOrlowski well, clearly, I am not using github "right". While I have managed to stumble thru, I would love a step by step guide that starts from forking a repo, covers how to branch, create a PR, respond to comments, update, and assuming the PR is accepted when I can dispose of the fork. Basically all the steps.

**Comment by MarcinOrlowski** [comment]
@dtowell Ok, I will add that to docs later today. Will keep you posted.

**Comment by MarcinOrlowski** [comment]
@dtowell  There are actually some [dev docs here[(https://github.com/logisim-evolution/logisim-evolution/blob/master/docs/developers.md#how-to-contribute) (look for "How to contribute" chapter). And if you prefer pseudo terminal session instead then this would be more like this (I already assume you have forked the LSe repository).

```bash
# go where you keep checked out forked repository
$ cd <YOUR-LSE-FORK>
# ensure you are on the develop branch
$ git checkout develop
# this one can be skipped if you have it. It adds upstream reference for easy updates from CLI
$ git remote add upstream git@github.com:logisim-evolution/logisim-evolution.git
# Ensure your copy of LSe is in sync with what we have
$ git fetch upstream
# if not, this one will merge our recent changes in your develop branch
$ git merge upstream/develop
# this will create new branch (I recommend you replace `1234` with bug ID you work on etc - helps managing your work
$ git branch -b my-contribution-1234
# here you do all your works needed
...
# once done you should test your works, build the LSe either from CLI or from IDE etc.
...
# you commit your changes as usual
$ git commit ....
# you push your works to github
$ git push
```

Now you need to send pull request. Please ensure it is against `develop` branch of ours. GH will by default set `master` there and it is not what it should target.

Voila. Hope this helps. If not, ask.

**Pull request closed without merging**
