### PR TITLE
A new language pack

### PR DESCRIPTION
**Pull request by legion-null**
I used machine translation and manual proofreading to make a Chinese language pack. At present, it runs very well on version 3.7.1. I added this language pack and hope that this project can be better promoted in Chinese-speaking countries, because Only after simple proofreading, there is no guarantee that there will be no errors.
我使用机器翻译加上人工校对的方法制作了中文的语言包，目前它在3.7.1版本上运行的很好，我添加这个语言包并且希望这个项目在汉语国家可以有更好的推广，因为仅仅经过简单的校对所以不保证没有错误。

### CODE REVIEW

**Review by BFH-ktt1 — APPROVED** [review]

**Comment by maehne** [comment]
Thanks a lot for this contribution @legion-null!

**Comment by CloverGit** [comment]
Hello, I spent a lot of localization translation on Logisim-evolution two months ago, but I have to suspend this work because of my personal study and work. I wonder if you are interested in improving this project. I hope to improve Logisim-evolution.
您好，我在两个月前花费了对Logisim进行了大量的本地化翻译，无奈因为个人学习工作原因不得不暂停这一工作，不知您是否有兴趣完善这一项目，我希望能完善Logisim。

**Comment by maehne** [comment]
Thanks @CloverGit for your offer to share the results of your localisation effort! For others, escpecially @legion-null, to pick up your work, it would be helpful if you could collect your results in a Git branch and point us to it. In addition, it would be helpful if you could provide a summary of the state of your work, i.e., which parts you considered complete and which require more work. We main maintainers can only formally review your contributions, as we don't have the necessary language skills.

**Comment by hewzhew** [comment]
Hi @legion-null, while updating the zh-CN docs we noticed one small issue from this original language pack: `baseLibrary` was translated as `基地`, which reads more like a physical base/camp. For Logisim's `Base` library, `基础` is the better short library name, matching the other short library names such as `线路`, `逻辑门`, and `存储器`.

I am fixing this as `baseLibrary = 基础` in #2579. No action needed from you; I am leaving this note here only for traceability. Thanks again for starting the zh-CN localization work.

**Pull request merged**
