### PR TITLE
Restore Sonar CI integration

### PR DESCRIPTION
**Pull request by zdimension**
Just noticed the Sonarcloud integration added in 49398d was somehow lost on develop.

### CODE REVIEW

**Review by MarcinOrlowski — COMMENTED** [review]
Where's config for Sonar?

**Comment by zdimension** [comment]
> Where's config for Sonar?

What do you mean? Everything is in the PR.

Again, this is not anything new, this was already reviewed and merged back in November. I'm only making a new PR because somehow my changes were lost on develop, through time and merges.

**Comment by MarcinOrlowski** [comment]
> somehow my changes were lost on develop, through time and merges

Can you please track down the PR/commit that removed Sonar last time? Do not really recall that but want to ensure it was not on purpose.

**Comment by zdimension** [comment]
> Can you please track down the PR/commit that removed Sonar last time? Do not really recall that but want to ensure it was not on purpose.

f715b9c7ae2083a0baa7d059dc6711bdf14e155d

**Review by maehne — APPROVED** [review]
Looks good to me!

**Pull request merged**
