### PR TITLE
Simplified code

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
There's no point for having the same, separate try/catch block for every method invoked

### CODE REVIEW

**Comment by davidhutchens** [comment]
That isn't the same logic. The original sets all that succeed. Your change sets those that succeed until one fails, then ignores the rest. Will that matter in practice? I don't know for sure, which is why I wrote it the way I did.

**Comment by MarcinOrlowski** [comment]
Yes, that's correct. I assumed now I all should succeed anyway. Do I miss something and even if some fail other can succeed and that's still fine?

**Comment by davidhutchens** [comment]
If you look at the documentation for the set operations on [Desktop](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Desktop.html#setPreferencesHandler(java.awt.desktop.PreferencesHandler)), you will see that they have different reasons why each might fail independently of the others. Of course, none of the reasons are very likely in this program. But I wrote the code to provide the maximum functionality allowed. Yes, it is fine to use those that succeed even if some fail.

**Comment by MarcinOrlowski** [comment]
Ok, thanks. Closing as my changes add no real value in such case.

**Pull request closed without merging**
