### PR TITLE
add final keyword to constants

### PR DESCRIPTION
**Pull request by R3dst0ne**
@zdimension was there a reason why you didn't use `final` in those places? (f4c2c035356123ecd56aa5f44e337b60ab426911)

### CODE REVIEW

**Comment by zdimension** [comment]
> @zdimension was there a reason why you didn't use `final` in those places? (f4c2c035356123ecd56aa5f44e337b60ab426911)
> 

Hmm, doesn't ring any bells, must have been an oversight on my part. These should definitely be final.

**Review by maehne — APPROVED** [review]
Looks good to me! Thanks @R3dst0ne!

**Comment by MarcinOrlowski** [comment]
What is the **real** benefit of this change? If class is not `final` so should not be consts?

**Review by MarcinOrlowski — APPROVED** [review]
LGTM

**Pull request merged**
