### PR TITLE
Add HDL support to Divider

### PR DESCRIPTION
**Pull request by jay20162016**
HDL support was already included, I simply enabled it.

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
Although the HDL-generator class is in the working tree, it has never been tested on correct functionality. This is the reason it is not enabled. It is on the todo list and will be enabled as soon as correct functionality is guaranteed.

**Comment by MarcinOrlowski** [comment]
>  It is on the todo list and will be enabled as soon as correct functionality is guaranteed.

@BFH-ktt1 can we have this PR closed unmerged then? Is there any ticket related to the above?

**Comment by maehne** [comment]
@MarcinOrlowski: As far as I can tell, there's no ticket regarding HDL generation for the divider.

**Comment by MarcinOrlowski** [comment]
@maehne can you create one so at some point we can have this addressed?

**Comment by maehne** [comment]
@MarcinOrlowski: Done

**Pull request closed without merging**
