### PR TITLE
Renamed all project methods to follow coding style

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
BLOCKED_BY #1161

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
I will resolve conflicts once #1161 is merged as these two overlap

* #1161

**Comment by BFH-ktt1** [comment]
I will merge #1161 once #1152 has landed, as they touch a lot of files I'm working on for the moment where there are a lot of changes. Maybe you can add a depend.

**Comment by MarcinOrlowski** [comment]
Done

**Comment by BFH-ktt1** [comment]
Super, thanks!
A small question on another topic, would it be possible to make a new method that does in a sence:

```LineBuffer.getBuffer().add(LineBuffer.getHdlBuffer());```

in the moment I have to do:

```LineBuffer.getBuffer().add(LineBuffer.getHdlBuffer().get());```

See my pushes in #1152 specially ```Nandgate.java``` and others in the same region

**Comment by MarcinOrlowski** [comment]
Am I correct you want to append content of one LineBuffer to another?

**Comment by BFH-ktt1** [comment]
> Am I correct you want to append content of one LineBuffer to another?

Yes, exactly

**Comment by MarcinOrlowski** [comment]
Here you go: #1166

* #1166

**Comment by MarcinOrlowski** [comment]
Let me know if that sufficient or you also would like to control the indentation (say, `lb1.add(lb2, 3)` which would be equivalent of `lb1.add(lb2.getWithIndent(3))`

**Comment by BFH-ktt1** [comment]
> Let me know if that sufficient or you also would like to control the indentation (say, `lb1.add(lb2, 3)` which would be equivalent of `lb1.add(lb2.getWithIndent(3))`

Super thanks! The getWithIndent is not required.

**Comment by MarcinOrlowski** [comment]
Ready for review.

**Review by BFH-ktt1 — APPROVED** [review]

**Pull request merged**
