### PR TITLE
Removes -Xlint:fallthrough from compiler options.

### PR DESCRIPTION
**Pull request by MarcinOrlowski**

### CODE REVIEW

**Review by BFH-ktt1 — APPROVED** [review]

**Comment by maehne** [comment]
@MarcinOrlowski: Could you please justify your decision to remove the fallthrough lint option? I added it on purpose as part of PR #575.

**Comment by MarcinOrlowski** [comment]
You can have this detected with CodeStyle, and as it is not the only thing remaining to be cleaned, I think it's better to have all offenses controlled from one place -> CodeStyle config.

**Comment by MarcinOrlowski** [comment]
Anyway, I did not know the reasoning (would have to have comment/link in Gradle file). While this may not result in different action, I'd at least know to ask first :)

**Comment by maehne** [comment]
My reasoning for using `-Xlint` options was to give developers instantaneous feedback for potential style issues while working offline on the code. If CodeStyle requires a different way of marking wanted fallthroughs, I am fine with deciding on one style checker.

**Pull request merged**
