### PR TITLE
Code formatting fix

### PR DESCRIPTION
**Pull request by MarcinOrlowski**

### CODE REVIEW

**Review by maehne — APPROVED** [review]
Looks good to me.

**Comment by MarcinOrlowski** [comment]
Interesting. For some reason I am unable to see the "Merge" action button and see "Only those with write access to this repository can merge pull requests.". Anything changed @BFH-ktt1 ?

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski , yes sorry, I adapted for the moment the rights, the reason for this is following:
We should define a proper workflow for the PR's, meaning that we should standardize this process. Up to the moment that we moved to the own organization it was quite simple as not many people were working on the project, and it was easy to handle. However, we are growing, and if the roles are not standardized, I think that we quickly lose track of all changes involved. It does not mean that I should be the one with "the power", but that we should standardize the procedure such that all involved can keep track without having to scroll through all the merged PR's. What do you think?

**Comment by MarcinOrlowski** [comment]
That's fine, just wasn't properly communicated :) Anyway yes, it's high time to have processes defined. As for PRs I personally would enforce no direct pushes neither to master nor develop and at least one mandatory reviewer per PR. Shall PR be accompanied by related mandatory issue/FR ticket is another story - I'd say, yes (as discussion should take place in the ticket there, not in PR where one should discuss the PR itself). That would also help avoid situations where there's some work already done (like #722) and it's unclear what to do with it. Mandating  ticket first would save some efforts, esp. in case of questionable changes. Finally, I'd also appreciate any feedback in #695 thread, as w/o roadmap (even roughly) defined, the project is dead from my perspective, despite current activity as "rolling deadlines" and "shotgun development" is not the way that leads anywhere.

**Comment by MarcinOrlowski** [comment]
Can we have this one either merged or rejected?

**Comment by BFH-ktt1** [comment]
Sorry, for the bad communication.

**Pull request merged**
