### PR TITLE
Corrects HexDisplay behavior. Closes #365

### LINKED ISSUE #365: Hex Digit Display: Improve visualisation of High-Z input value
Doing some tests with Hex digit display, I noted that if the data (4 bit) is in High-Z, display shows "H" instead of stay in adjusted "Off Color". It would be good if the Hex digit display works like the 7-segment display. Moreover, it would be nice to have the option "Active On High?" as the 7-segment display has.

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
Changes HexDisplay behavior:
* display is blank if no valid input is given
* changed shape of "error" (OOB) value from "dash" to "three dashes" to avoid confusion.

Fixes #365

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski , Is the documentation part also updated to reflect this change? Maybe we should also add this at least for the English documentation, or make a kind of "documentation update note" where we indicate which part of the documentation should be updated/added with which contents. What do you think?

**Comment by MarcinOrlowski** [comment]
I just updated the documentation. BTW: I noticed that German docs for HexDigit is just copy of English text (in English), with headers in German. That's useless. We should check the state of the docs. In fact, I think I'd be far better to separate docs from the app and keep it on-line (github pages?) to avoid such issues. I will create ticket for this.

**Comment by maehne** [comment]
There have been proposals in this direction in the past. In any case, creating a real homepage for Logisim-evolution is on our wish list. I agree that GitHub Pages is probably the easiest to maintain solution. [Docusaurus](https://docusaurus.io) was proposed by one contributor as a framework, as it apparently supports well documentation translated into several languages. We should plan this as part of our Roadmap discussion. Using a web browser to display the documentation is fine, but I would like that it is still possible to do so offline, i.e., the documentation is distributed as part of Logisim-evolution.

**Comment by maehne** [comment]
By the way, @BFH-ktt1 and myself won't have much bandwidth till next Thursday due to exams and grading them.

**Comment by MarcinOrlowski** [comment]
It's mostly about ease of updating the docs. We can anyway generate something from the HTML. Anyway, will add to ROADMAP agenda.

>  till next Thursday due to exams and grading them.

Can we at least have go/no-go for #795 as this blocks me from touching the code now.

**Comment by MarcinOrlowski** [comment]
@maehne Anything left to do here?

**Comment by MarcinOrlowski** [comment]
Created #824 to address docs issues

**Pull request merged**
