### PR TITLE
libraryRemove() refactoring

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
This PR adds default implementation of `removeLibrary()` and removes all the reincarnation of this code

DEPENDS_ON #974

### CODE REVIEW

**Review by BFH-ktt1 — APPROVED** [review]
To be merged after the release. @MarcinOrlowski is there a possibility to make a depend on a release date, this would help in sorting out the PR's that can be merged before the new release, and the ones afterwards.
I could think of a PR that "bumps to version V3.6.0", but maybe there is a more intelligent way?

**Comment by MarcinOrlowski** [comment]
There's not but you can create separate PR like "Release 3.6.0" and PR like this one can be then set dependent on "Release 3.6.0" PR which will be merged after release 3.6.0

**Comment by MarcinOrlowski** [comment]
or maybe also add Milestone "3.6.x" and attach to it? but that do not prevent merging, so former idea is probably more concrete.

**Review by maehne — APPROVED** [review]
LGTM

**Pull request merged**
