### PR TITLE
Add 74151, 74279, 74682, and 74688 74-series ICs

### PR DESCRIPTION
**Pull request by jdah**
Adds support for

- 74151 (4-bit counter with async reset)
- 74279 (Quad SR latch)
- 74682 (8-bit comparator with < and =)
- 74688 (8-bit comparator with OE and =)

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
Thanks for you contribution. Could you each IC as separate PR please? That would help us a lot.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
Thanks for your contribution. Could you each IC as separate PR please? That would help us a lot.

**Comment by MarcinOrlowski** [comment]
Also, I noticed that you made your changes in `master` branch. That's not correct. You must checkout `develop`, branch it, do your changes and send your PR against our `develop`.

**Comment by jdah** [comment]
Ah my bad on the branch checkout, I didn't realise I should merge into develop - will close this one, separate the ICs out into separate PRs against `develop` :)

**Pull request closed without merging**
