### PR TITLE
Update library documentation

### PR DESCRIPTION
**Pull request by mbaillif**
This is the first step of the update
Mainly HTML normalization and image updates

### CODE REVIEW

**Comment by mbaillif** [comment]
And it's possible to check that the name of the icon files is updated in lower case. /doc/icons/6464 or /1616
I don't know if Git does this kind of synchronization.
If it doesn't, I think to delete the files in a PR and then add them in a second PR

**Comment by mbaillif** [comment]
I don't understand this problem with Gradle

**Comment by MarcinOrlowski** [comment]
> I don't understand this problem with Gradle

My bad.  #768 fixes that. Sorry.

**Comment by R3dst0ne** [comment]
> And it's possible to check that the name of the icon files is updated in lower case.

Git can detect such changes, to insure it use [`git mv`](https://git-scm.com/docs/git-mv).

**Comment by MarcinOrlowski** [comment]
@mbaillif builder is fixed, but if you want checks to be redone you need to make another push to trigger all the actions.

**Comment by mbaillif** [comment]
Okay, thank you, :-)

**Comment by mbaillif** [comment]
Normally there are no build needs. 
I only modified png or html files

**Pull request closed without merging**
