### PR TITLE
Encapsulate library components

### PR DESCRIPTION
**Pull request by R3dst0ne**
Created folders for each component in a library.
And moved the BFH library from [fpga/function](https://github.com/logisim-evolution/logisim-evolution/tree/develop/src/main/java/com/cburch/logisim/fpga/library) to [std/bfh](https://github.com/R3dst0ne/logisim-evolution/tree/encapsulate_library_components/src/main/java/com/cburch/logisim/std/bfh).

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
Did you remove and the added the files instead of `git mv`?

**Comment by MarcinOrlowski** [comment]
Also be aware of #657

**Comment by R3dst0ne** [comment]
> Did you remove and then added the files instead of `git mv`?

Yes, I used a script to do most of the work for me and then manually checked it. Honestly, I didn't think about that I could edit my script to use `git mv`. I could do another PR doing the same changes with `git mv`, when you think this is a real problem.

#657 and #663 should be able to merge without problems.

**Comment by MarcinOrlowski** [comment]
Main only concern is retaining change history for the files you moved.

**Comment by R3dst0ne** [comment]
good point. I will do it again.

**Pull request closed without merging**
