### PR TITLE
Fixing the random number generator (64-bits)

### PR DESCRIPTION
**Pull request by BFH-ktt1**
This PR addresses #522

DEPENDS_ON #974

### CODE REVIEW

**Comment by R3dst0ne** [comment]
This is funny, I started working on this yesterday and implemented [xoshiro256++](https://prng.di.unimi.it/).
I just logged on to open a draft ^^'

**Comment by BFH-ktt1** [comment]
@R3dst0ne : Please go ahead, could you also implement the HDL-generators? In this way I wil concentrate on testing the HDL-generators of the components not tested yet

**Comment by R3dst0ne** [comment]
Ok, I already partially implemented the HDL-generator for xoshiro256++.
I will do view cleanups and open a draft tomorrow.

**Comment by BFH-ktt1** [comment]
@R3dst0ne : On a site note, I fixed some small bugs in Random.java, you might want to take a look in my changes to this file. Mainly it concerns the reset behavior (the state does the reset on a rising edge of the reset signal, but it did not "block" the clock in case the reset was at high level, this I fixed).

**Comment by R3dst0ne** [comment]
@BFH-ktt1 
Do you want this issue fixed before the new release?
If yes, I need to now because I then have to implement a solution that is not ideal but working.
Otherwise, I would use some more time to figuring out the best wayto do it.

**Comment by BFH-ktt1** [comment]
@R3dst0ne : This would be for after the next release, the current RNG is working (although only 32 bit). So take your time

**Comment by BFH-ktt1** [comment]
I'll close this PR, as @R3dst0ne is working on it.

**Pull request closed without merging**
