### PR TITLE
Cleaning up the HDL-generator removing a lot of none required LOCs

### PR DESCRIPTION
**Pull request by BFH-ktt1**

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski: could you take a look already?
I have 1 question: In the constructors, do I have to imply the ```super();``` or can I omit it as it is called automatically.
Than 1 comment: In this PR I will not refactor already all classes, as it will be big already.

**Comment by MarcinOrlowski** [comment]
`super()` is not called automatically and usually you need to call it in your child class' constructor to let parent class set up first. But if you do not extend, nor you are sure parent do not need any setup, calling `super()` can be omitted as default constructor does nothing anyway.

**Comment by BFH-ktt1** [comment]
Thanks, so in these cases they are required, as the super class does an important initialization.

**Review by maehne — APPROVED** [review]
LGTM

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski : could you review?

**Review by MarcinOrlowski — APPROVED** [review]

**Pull request merged**
