### PR TITLE
Encapsulate library components

### PR DESCRIPTION
**Pull request by R3dst0ne**
Created a folder for each component in a library and moved everything with `git mv`.
Moved the BFH library from [fpga/function](https://github.com/logisim-evolution/logisim-evolution/tree/develop/src/main/java/com/cburch/logisim/fpga/library) to [std/bfh](https://github.com/R3dst0ne/logisim-evolution/tree/encapsulate_library_components/src/main/java/com/cburch/logisim/std/bfh).

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
Moving `fpga/function` to `std/` may be a good thing (but I also think I see the point why it sits where it sit now). But what's the point of this commit `individual folder for each component in library`?

**Comment by R3dst0ne** [comment]
Some components have up to 4 files and I think it is better to have them together. It also makes the libraries much cleaner.

One thing I'm unsure about is how to handle classes that are used by multiple components. Currently, I gave them their own folder with the name of the file containing them.

**Comment by MarcinOrlowski** [comment]
Many are single `*.java` files. And they are happy together now in library category folder :) Also classes that belong to one tool/component usually share parts of the class name prefixes (i.e. `Led.java`, `LedShape.java`), so files are shown together in the folder tree too.

In fact this change would make navigating thru files harder. If you'd like to i.e. see all the files in the sub-category it would  need twice as much screen space (with the `TTLs` being a nightmare example) because of these sub-folders.

I think that better (from the dev standpoint) type of cleanup would rather be something like this:
* rename Library classes to contain "Library" suffix (i.e. `Ttl.java` -> `TtlLibrary.java` and so the class name)
* drop the `Abstract` prefix from abstract classes and replace it with `Base` suffix (i.e. `AbstractGate` -> `GateBase`) 
* move all the above base classes to base sub-package for each library category.

BTW: I'd also suggest splitting this PR into two separate ones as these changes are not coupled really.

**Comment by R3dst0ne** [comment]
> In fact this change would make navigating thru files harder.

I would say the exact opposite. ^^ In my opinion, it makes navigating and finding the needed files much easier (Except shared classes. I will think about a better solution). This probably comes down to personal preference.

> If you'd like to i.e. see all the files in the sub-category

This is something rarely needed. When needed, is simply done with a tree representation of the category.
I agree that the TTL Library is worse now. I thought about not changing it but decided to do it for consistency’s sake.

<br>

> rename Library classes to contain "Library" suffix (i.e. Ttl.java -> TtlLibrary.java and so the class name)

This is a good Idea.

>drop the Abstract prefix from abstract classes and replace it with Base suffix (i.e. AbstractGate -> GateBase)

If this PR gets rejected, this is a good idea. When it gets accepted, it could be done but is not really important.

**Comment by MarcinOrlowski** [comment]
> In my opinion, it makes navigating and finding the needed files much easier

I still find this change artificial and IMHO not driven by real needs. And I am saying it makes navigating harder as you need one more action (click on folder or folder unfolded other way) and you are unable to see the whole picture of the library without that. If you know what you class/file are looking for, any sane IDE got shortcuts for this (i.e. InteliJ double <kbd>SHIFT</kbd> in InteliJ).

So if I'd vote then 👍🏻 for move of BFH (+ adding "Library" suffix to library classes) and 👎🏻 for subfolders.

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski : Thanks for the work, could you just look into the conflicts, such that I can merge?

**Comment by MarcinOrlowski** [comment]
@BFH-ktt1 Please do not merge yet. Also do you mind (and perhaps other active participants too) joining the conversation about the necessity of this PR? In particular, the part about creating separate sub folders for each library element which (again, IMHO) adds no value.

**Comment by BFH-ktt1** [comment]
Sorry was to fast in my last remark. For my part I agree with @MarcinOrlowski when he says:
👍🏻 for move of BFH (+ adding "Library" suffix to library classes) and 👎🏻 for sub-folders.
As than we would have 1 or 2 java files each sub-folder. This adds, in my opinion, no extra functionality or better overview. Currently the libraries are, as is, quite slim (except for the TTL-library, but here are a lot of components.

**Comment by BFH-ktt1** [comment]
Can this pull request be closed?

**Pull request closed without merging**
