### PR TITLE
Add png screenshots for Flatpak

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Related to https://github.com/logisim-evolution/logisim-evolution/issues/743, this MR is to use the new screenshots for Flatpak that was suggested by https://github.com/logisim-evolution/logisim-evolution/issues/678#issuecomment-871757125.

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
If we can't have WEBP with Flatpak, then I suggest to completely replace WEBP images with PNG, remove WEBP from repo and update docs (*.md) to use PNG Instead. Having two files with the same content makes no benefits.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
If we can't have WEBP with Flatpak, then I suggest to completely replace WEBP images with PNG, remove WEBP from repo and update docs (*.md) to use PNG Instead. Having two files with the same content makes no benefits.

**Comment by TheEvilSkeleton** [comment]
I'm on it.

**Comment by TheEvilSkeleton** [comment]
Only downside is that the replacements take more space than the former screenshots. I hope that's okay.

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski @TheEvilSkeleton : How do we want to go about this one, replacing all WEBP images by png (I think it makes sense) or merging this PR and having 2 sets of images?

**Comment by MarcinOrlowski** [comment]
We do not want to maintain two set of images as this would give us nothing but headaches. The size difference was the reason I chosen WEBP but since I do not see Flatpak docs to mention anything else than PNG and SVG we can get away with PNGs. Traffic is not a problem for the project anyway.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
Please update `*.md` files to refer to PNG images.

**Comment by MarcinOrlowski** [comment]
Interesting that MD LInter did not complain here. Need to check that.

**Comment by TheEvilSkeleton** [comment]
> Please update `*.md` files to refer to PNG images.

What MD files refer to webp? GitHub search doesn't work properly.

**Review by MarcinOrlowski — APPROVED** [review]
LGTM

**Review by maehne — APPROVED** [review]
Looks good to me!

**Pull request merged**
