### PR TITLE
Sync *.properties

### PR DESCRIPTION
**Pull request by R3dst0ne**
In  #722 we forgot to sync the *.properties files.

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
> add missing CR LF 

why CR LF?

**Comment by R3dst0ne** [comment]
Because there is a newline at the end of the other files, and GitHub doesn't like it when it is missing.
`CR LF` is short for `carriage return line feed`(windows newline standard).

**Comment by MarcinOrlowski** [comment]
While codebase is LF based. So CR LF is not the best choice.

**Comment by R3dst0ne** [comment]
You are completely right.
The files use only `LF`, I used the wrong name and didn't think about it.
To my knowledge, Git enforces this automatically.

**Review by MarcinOrlowski — APPROVED** [review]

**Comment by MarcinOrlowski** [comment]
LGTM

**Review by zdimension — APPROVED** [review]

**Pull request merged**
