### PR TITLE
Updated logisim icon

### PR DESCRIPTION
**Pull request by TheWeirdSquid**
New pull request for issue https://github.com/logisim-evolution/logisim-evolution/issues/1651.

An issue with the .icns file was highlighted by @davidhutchens in the previous pull request. The .icns file is also generated by 'artwork/update_assets.sh', and I'm not familiar enough with the project to fix it. My suggested solution is to modify the script so that it doesn't build the macOS icon at all, but I'll leave it to people who are more familiar with the project.

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
@TheWeirdSquid  I am not Mac user myself but I wrote generating script so can you please link to these Apple's guidelines so I could see how to update the script?

**Comment by TheWeirdSquid** [comment]
@MarcinOrlowski Here's the link to the guidelines: https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/. The guidelines have a lot of rules for making sure the app icon is consistent across platforms, but since this isn't an App Store app and the program only supports MacOS, we don't have to worry about cross-compatibility.

However, the guidelines themselves are pretty simply summed up with the following: 
1. A program icon should be shaped as a rectangle with rounded borders of a certain size
2. MacOS icons should be abstract in design yet still incorporate some 3D elements.
3. You can have a tool or some other item over top of the icon. This is allowed for in the icon size, but this isn't applicable to the logisim logo. For an example of what this means, see the [garageband logo](https://upload.wikimedia.org/wikipedia/en/f/f7/GarageBand_App.png) and the [chess logo](https://help.apple.com/assets/61E87C901BD92B410A70E5B0/61E87C911BD92B410A70E5B7/en_US/3fb2a3616e2d382e45a5f146374f8615.png)
4. Make sure that smaller resolutions of the icon are still recognizable. This may require reducing detail at smaller resolutions.

Since logisim evolution is not on the App Store, these guidelines are more along the lines of suggestions to make the app blend in on the OS. 

image
I've created a version of the logisim evolution logo that fits these guidelines (shown above). However, it is not possible to build it from the original logo svg. It is a separate image entirely (rendered in Blender). Note that the actual blender file is attached to the issue I originally opened in case future modifications need to be made.

To my best understanding, here is how your script currently works:
1. It compiles the svg icons to png files of various sizes.
2. For the MacOS build, it compiles those PNGs into a .icns file and replaces the file at support/jpackage/macos/Logisim-evolution.icns.

However, I've already built that file manually using my own renders of the new icon. It should be sufficient to simply comment out the part of your script that builds the MacOS icns file, since it does not need to be generated. 

Hopefully this helps explain the issue. I would have made the changes myself, but I'm not familiar enough with the project to foresee any extra issues that might cause with the build process.

**Comment by maehne** [comment]
@TheWeirdSquid: Thanks for your effort designing a new application logo for Logisim-evolution for use on macOS! Having to use Blender as a requisit to modify/update it further in the future is quite heavy. Would it be possible for you to do the same design in [Inkscape](https://inkscape.org/) so that we get an SVG version like for the other platforms? The icon is quite flat so that I don't see the advantage of using Blender. Having an SVG, would simplify creating different resolutions of the icon for `.icns` file.

**Comment by TheWeirdSquid** [comment]
Blender was used because the MacOS style guidelines specifies that app icons should have 3d texture and depth. That is very hard to replicate in an SVG and I don't have the skills to do it. I'd also point out that the file I'm trying to merge is a .icns file, not an image. It already contains every resolution. There is no need for post processing on the icon.

**Review by BFH-ktt1 — APPROVED** [review]

**Pull request merged**
