### PR TITLE
Removed alternative HDL bracket placeholders

### LINKED ISSUE #969: Drop support for alternative form of HDL bracket placeholders
Currently LineBuffer's HDL placeholders offers `{{openBracket}}` and `{{closeBracket}}` and equivalent `{{<}}`/`{{>}}`. We shall keep only one, so unity usage across strings/text blocks and remove support for deprecated placeholder.

BLOCKED_BY #968 
BLOCKED_BY #952

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
Closes #969

* #969

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@ R3dst0ne , what is your opinion?

**Review by BFH-ktt1 — DISMISSED** [review]

**Comment by R3dst0ne** [comment]
I'm for having no duplicates. Removing one is the right way.
But my opinion since
>I'm in favor of the more descriptive placeholders ({{openBracket}}), the other ones could mean a lot of things.

has not changed.

**Comment by MarcinOrlowski** [comment]
> I'm in favor of the more descriptive placeholders ({{openBracket}}), the other ones could mean a lot of things.

Please start using these placeholders and come back if you face **real** ambiguation case.

**Comment by BFH-ktt1** [comment]
What do we do with this PR? I would suggest to close it and look how #1057 works out

**Comment by MarcinOrlowski** [comment]
I'd actually merge it because if you look at diff then you that we did not use "bracketOpen" and "bracketClose" almost at all, so removing it will clean things up. Will we change `{{<}}` `{{>}}` placeholders in future or not is another story and another PR.

**Review by BFH-ktt1 — APPROVED** [review]

**Pull request merged**
