### PR TITLE
Feature: Tick frequency is preserved in .circ file (take 2) (to go into release 3.6.0)

### PR DESCRIPTION
**Pull request by BFH-ktt1**
same as #1018 but now targeted for the release version 3.6.0. It makes sense to intergrate this feature already in v3.6.0 as it simplifies some tasks in usage and correction.

* #1018

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
This is new feature - why you push it into frozen 3.6.0?

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski : I agree with all your points. I just put it here for the case that everybody agrees that this is a nifty feature to have already in v3.6.0. I leave it open for the moment to get feed-back of the others. As this feature simplifies a lot some practical works we do next semester I opted for integration.
What do you all think ?

**Comment by MarcinOrlowski** [comment]
If the feature is nice to have, let's freeze 3.7.0 once we release 3.6.0 so it will be out pretty quickly anyway. We do not have fixed release schedule so that's fine.

**Comment by BFH-ktt1** [comment]
> If the feature is nice to have, let's freeze 3.7.0 once we release 3.6.0 so it will be out pretty quickly anyway. We do not have fixed release schedule so that's fine.

It is not very practical to ask the students to change versions during the semester (it often get's a mess with a mangling of installed versions). We normally only do this in case of a "serious" bug. So V3.7.0 will not be there (for the students) before the end of the semester (hence feb. 2022).

**Comment by MarcinOrlowski** [comment]
Well, if you insist that you want that one from the start then OK. But I will object that "So V3.7.0 will not be there (for the students) before the end of the semester (hence feb. 2022)." because we should not sync releases with academic semester. The fact there's 3.7, 3.8 or whatever do not mean students must update. You may still want tell them to stick to 3.6 for the semester.

**Comment by R3dst0ne** [comment]
> because we should not sync releases with academic semester.

When I understand him correctly, then this is not what he meant to say.

> So V3.7.0 will not be there (for the students) before the end of the semester (hence feb. 2022).

Means that they have to stick with 3.6.0 even when newer ones get released. And that means that he/them have to wait at least  half a year before this useful feature can be used.

I'm for introducing it in 3.6.0.

**Comment by MarcinOrlowski** [comment]
> will not be there (for the students)

Thanks @R3dst0ne, you're right. I missed "(for the students)" thing. Forget my rant then :)

**Review by MarcinOrlowski — APPROVED** [review]

**Pull request merged**
