### PR TITLE
Remove "Printer view" from Preferences->Layout #1437

### LINKED ISSUE #1437: Remove "Printer view" from Preferences->Layout
We had so far 3 tickets (issues #862, #1324, #1434) plus several occasions in the classroom, where users thought simulation was broken in Logisim-evolution due they had inadvertently activated "Printer view" in Preferences-> Layout. So, it seems that this functionaly is causing more confusion than added value. I see its only value when exporting circuits as an image. IMHO, we should either remove the option "Printer view" from Preferences->Layout or add a very explicit warning about the undesired effect in the Layout tab or when activating the option.

### PR DESCRIPTION
**Pull request by dtowell**
Fixes #1437

* #1437.

### CODE REVIEW

**Comment by R3dst0ne** [comment]
Please remove [`layoutPrinterView`](https://github.com/logisim-evolution/logisim-evolution/blob/f1ae40ba1a8601efe0cda6f8a92631038c03dc95/src/main/resources/resources/logisim/strings/gui/gui.properties#L546) from the properties files in [src/main/resources/resources/logisim/strings/gui/](https://github.com/logisim-evolution/logisim-evolution/tree/develop/src/main/resources/resources/logisim/strings/gui).

**Comment by MarcinOrlowski** [comment]
Is there any related ticket on why this is going to be removed?

**Comment by MarcinOrlowski** [comment]
@maehne Thanks.

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
As per @R3dst0ne [comment](https://github.com/logisim-evolution/logisim-evolution/pull/1486#issuecomment-1189684131):

Please remove [layoutPrinterView](https://github.com/logisim-evolution/logisim-evolution/blob/f1ae40ba1a8601efe0cda6f8a92631038c03dc95/src/main/resources/resources/logisim/strings/gui/gui.properties#L546) from the properties files in [src/main/resources/resources/logisim/strings/gui/](https://github.com/logisim-evolution/logisim-evolution/tree/develop/src/main/resources/resources/logisim/strings/gui).

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
@dtowell thanks for updating the PR but I am not convinced this PR is complete. I got a feeling that you just removed ability to turn on/off printer view but I see no other changes like removing any code that would handle printer view. Can you please correct that too?

**Comment by davidhutchens** [comment]
@MarcinOrlowski The printer view control in preferences causes problems. The correct way to use printer view is in the print dialog. The code that actually produces the printer view is quite useful and should not be removed.

**Comment by MarcinOrlowski** [comment]
@davidhutchens Ok, I went one bridge too far then. Thanks for clarification.

**Review by MarcinOrlowski — APPROVED** [review]

**Pull request merged**
