### PR TITLE
Adds Lombok + code cleanup

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
SQUASH merge recommended.

All-time favorite: cleanup PR. This one adds [Lombok](https://projectlombok.org/) to the project. If you are unfamiliar, see the linked side, however from all the features we mostly need these: `val` (instead of `final var`) and `@Setter` and `@Getter` instead of writing dumb accessors. `@Data` to remove boilerplate code from POJO type-of-classes, and `@EqualsAndHashCode`.

### CODE REVIEW

**Comment by davidhutchens** [comment]
I read your docs update. I followed the link to the lombok page where I downloaded the lombok.jar and followed its instructions to run the installer to update my Eclipse. The installer clearly did what it said it would do by putting the jar in the Eclipse app and adding a line to the eclipse.ini file.

However, when I launched Eclipse and tried to display a file, the eclipse editor threw an exception and failed to load, even on a project that didn't use any lombok features. It didn't even get around to looking at the code to be edited.

After searching for fixes, I eventually found [closed lombok issue 2810](https://github.com/projectlombok/lombok/issues/2810) that noted that the released version of lombok is not compatible with Eclipse+Java16. That issue is fixed in the current build and a pre-built version is linked in issue 2810. That version works for me to edit simple files; but I haven't yet tried it on this PR.

My experience does illustrate some of the problems with using third party language extensions. They can allow for cleaner and simpler code; but there are risks which should be weighed against the benefits.

That said, on the benefit side, lombok does seem to provide several things I've wanted to write a macro for in Java.

**Comment by MarcinOrlowski** [comment]
Thanks for the feedback. Please let me know if you have any other problems with Lomboked code in  Eclipse. If that was the only one, I will update the docs to cover that.

**Comment by BFH-ktt1** [comment]
I'm not against using Lombok, however, I share the concern of @davidhutchens : 

```My experience does illustrate some of the problems with using third party language extensions. They can allow for cleaner and simpler code; but there are risks which should be weighed against the benefits.```

and hence I think we should discuss these kind of changes in the roadmap discussions.

Furthermore, on another note, such "large" PR's are very difficult to review due to the large number of files touched and large number of changes. I think that we should try to do smaller PR's in order to have a higher review quality.

**Comment by MarcinOrlowski** [comment]
If we decide to go with Lombok, I will create a few smaller PRs based on this one. Converting to draft for now.

**Comment by maehne** [comment]
I share the concerns of @davidhutchens and @BFH-ktt1. In addition to potential stability issues, which may get introduced by the Lombok extension into the IDE used by our developers, it may also increase the barrier to potential first-time contributors. Also by forcing on them this tool, we are also limiting their choice for the IDE. E.g., some of our developers may still be fans of Emacs (I count myself to this group) and vi.

**Comment by MarcinOrlowski** [comment]
I updated this PR to the HEAD of `develop/`. PTAL.

**Comment by MarcinOrlowski** [comment]
@BFH-ktt1 Can we have this one merged? If you never worked with Lombok, try and you will see that it is intuitive. And if at any point we decide to unplug it, it's very simple to do (I think it is even automated).

**Comment by BFH-ktt1** [comment]
I'll look tomorrow morning into the details (I want to check this branch in eclipse before merging). Now I have to leave. Is this okay?

**Comment by MarcinOrlowski** [comment]
Sure, that fine. Thanks.

**Comment by BFH-ktt1** [comment]
Okay, had some time and did some test.
With the current version of lombok (1.18.20) it does definitely not work. You have to install the version 1.18.21 found in the link @davidhutchens shared above (https://github.com/projectlombok/lombok/issues/2810). Than it compiles.
Hence I am still in doubt and want to hear from @maehne , @davidhutchens if it is a yeah or no before merging.

**Comment by MarcinOrlowski** [comment]
Made Lint happy

**Pull request closed without merging**
