### PR TITLE
Release Version v3.6.0

### PR DESCRIPTION
**Pull request by BFH-ktt1**

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
Tested on all platforms, linter can be ignored

**Review by MarcinOrlowski — APPROVED** [review]

**Comment by R3dst0ne** [comment]
@BFH-ktt1 
@maehne  and I both asked for reverting the new icon (#884). ([here](https://github.com/logisim-evolution/logisim-evolution/issues/884#issuecomment-910159997) and [here](https://github.com/logisim-evolution/logisim-evolution/issues/884#issuecomment-910347195))
A view points why this definitely should be done can be found in my [comment](https://github.com/logisim-evolution/logisim-evolution/issues/884#issuecomment-910347195).

**Comment by R3dst0ne** [comment]
Did I miss it, or was there no announcement when you plan on releasing 3.6.0 ?
The only thing I found was [this](https://github.com/logisim-evolution/logisim-evolution/discussions/972#discussioncomment-1255390) and because of that I thought I still had a view days left to work on the translation and correct a view mistakes in the documentation. (These changes are not really important.)
IMHO, this PR should have been reviewed by more than two people, because then it is more unlikely that things that still need to be done get forgotten (E.g. the icon).

**Comment by MarcinOrlowski** [comment]
Since it is already released, let see the users feedback. Also it's now time to discuss the branding if that's need any discussion before next release.

**Comment by R3dst0ne** [comment]
> Since it is already released, let see the users feedback. Also it's now time to discuss the branding if that's need any discussion before next release.


I totally disagree.
This should have been discussed before the new icon even got introduced.
And there is definitely a discussion needed since multiple people already said they against it, or we should at least discuss this properly.
The release is only a view hour old, so changes can still be done without problems. If we wait and discuss it in near future, the damage will already be done.

This "branding" afford is mainly pushed by @MarcinOrlowski, and I'm heavily against that something pushed by only one person gets in the new release, when a others demand a discussion first. A revert was demanded/planed multiple times and @MarcinOrlowski always blocked them until it finally slipped in the release.

Maybe I'm a little too invested in this, but this goes against my beliefs how such things should be done.

**Comment by BFH-ktt1** [comment]
Okay, there are several points here that I want to address:

1) "Branding". This is a point I do not care. If there are some amongst you who want to do a branding effort, please go ahead, discuss and put the points in a discussion thread.

2) Up to this moment I accepted (with rare exceptional cases) all PR's, being it features, GUI changes, etc. I think that we should keep this dynamic open and not have each time endless discussions. There will always be things that some like and others not.

3) I'm not used, for the moment, to have more actively people involved, as I mainly pushed myself (with discussions with @maehne ) this project for the last 4-5 years (with of course help from a lot of great contributors). Please give me some time to adapt to the new situation, I will still make here and there some errors.

4) Than the icon story: First of all I see one person strongly against (@R3dst0ne), and one person strongly in favor (@MarcinOrlowski). I basically see following advantage in the new logo: The old one was nearly invisible on dark themes, and the new one is clear on both dark and light themes. Also it does not differ too much from the old one. So in accordance with my point 2) above I left it in. And here I agree in a certain way with @MarcinOrlowski 's argument ```let see the users feedback```, if they don't like it we can always revert back.

5) Release date: As there were the whole week no PR's on the rc_3_6_0 branch (the release candidate), except from some bug fixes (and added feature) from myself and @MarcinOrlowski, I used my last free Sunday to prep. everything and test all on the three different platforms (windows, linux, and Mac-OS). Starting from tomorrow I will be again "burried" in preparations for the next semester and will not have much time for extensive work on logisim. Also in our meeting we (I) agreed beginning of September and latest the 13th.

@R3dst0ne : I understand your "anger", but this is in no way a deciding by 2 story, in the contrary I think that we are stating to make progress in direction of being a bigger active community. I hope that I could explain a bit my point of view. 

And there are points to be discussed, with on the top:

1) Lombok or not. As this will have a big impact on the code base and development.

2) Documentation external or internal. As this will have a big impact on how to structure the documentation and how to go forward in the documentation effort.

**Comment by MarcinOrlowski** [comment]
Let's discuss docs separation here -> #824 
Let's discuss branding here -> #1052

* #824 
* #1052

**Comment by MarcinOrlowski** [comment]
I am **not** defending current logo. I am against doing random changes that adds no value. I hope that we all see the point of the unique branding. How it looks is another story. Even if one do not like current icon or logo then one thing is indisputable - it differs from any other LS fork (incl. base version). If anyone with better ideas change this and we all agree the change is an **improvement**, then I'd be more than happy to vote for it too.

**Comment by MarcinOrlowski** [comment]
I am locking discussion here. Please keep things going in designated threads as linked above.

**Pull request merged**
