### PR TITLE
Revert "Refactord data classes to use Java 16's records."

### PR DESCRIPTION
**Pull request by BFH-ktt1**
Reverts logisim-evolution/logisim-evolution#1149

### CODE REVIEW

**Comment by MarcinOrlowski** [comment]
What wrong with records?

**Comment by BFH-ktt1** [comment]
With records there is nothing wrong, but it is important that people can work on their preferred platform on the source code. Going on the edge is a good thing, but keep in mind that we also have students that want to contribute. Having a setup that does not require to update every month (or more often) your development environment helps. Introducing new features is fine with me, as long as it is tested on common ide's (eclipse included). Each change I made in the past I tested extensively on the hardware and on the three platforms (and even with this some bugs were left in V3.6.0). I think that we need to go to more extensive testing as just "it builds with gradle", what do you think?

**Comment by MarcinOrlowski** [comment]
Record class type is stable language feature as of JDK16 (incubating since JDK14) and we require JDK16 already, so no reason to not use what language offers, esp. it reduces number of boilerplate code as you can clearly see. And reducing verbosity and decreasing LoC is always a good goal.

As for tests - we need automated tests. Test-by-compilation is definitely insufficient, do agree. But we aware that writing proper testing is often more work than writing the software under test. Also current implementation is painful for testing at the moment. I will still need to do a few more cleanup rounds before I add i.e. dependency injection framework. without that, mocking of most of  the components will be huge P.I.T.A.

**Comment by BFH-ktt1** [comment]
Agree that it is a stable language feature as of JDK16, but that does not mean that it is also directly supported in current IDE's, as you could see in the post of @davidhutchens , we had to upgrade eclipse to a new version to have it available. Eclipse is an environment that is widely used by students, and hence we need to keep track which minimal version to use to be able to use the IDE. This goes in the same direction as the discussion on using language extensions. I know this is in some way restricting (like using VHDL93 instead of the latest version, but it is still the only one compatible with all software tools). Maybe I'm wrong, conservative, or just rambling stuff.

**Comment by MarcinOrlowski** [comment]
It's always good to have wider perspective, so I appreciate your feedback. But if we require JDK16, and we do, then it means you if you want to contribute should be a) know what JDK16 offers (that helps) but b) you should be using tools that understand said JDK16. If you choose to stick to older tools for any reasons, it that's **your** problem and your problem only. Eclipse do support JDK16 since 2021-03 (4.19) so it's there. Just upgrade.

**Comment by davidhutchens** [comment]
Part of the problem is that Eclipse 2021-03 (4.19) claimed to support JDK 16; but it didn't really. I was using 2021-03 (4.19) and had to upgrade to get it to allow me to properly set everything to JDK 16 so I could actually compile with records.

Essentially, using a JDK version that is only a few months old means that there are issues with various related tools until those get worked out.

"Just upgrade" makes sense to you; and I had no problem doing that, after I figured out I needed to. But getting several dozen students to get to the right place involves more instructor time than you might think; and it annoys the students. Luckily, students don't need to update an IDE to use LSe. But they might need to in order to contribute to the project.

No one is suggesting we back up to an earlier JDK. But there is a lesson here about the issues of living on the cutting edge. Like all things in software engineering, there are tradeoffs.

**Comment by MarcinOrlowski** [comment]
To sum up. We are at JDK16 and most likely stay here for a while. Let's hope Eclipse catch up quickly :)

**Pull request closed without merging**
