### PR TITLE
Adds support for pre-commit hooks

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
As log of PR's commits are about addressing linters' complains, I decided to use [pre-commit](https://pre-commit.com/) to prevent such changes from even being commited. pre-commit hooks into git pipeline and runs several checks to ensure commit can be made. I also updated docs with info on how to install pre-commit on developer machine. 

For now, aside from generic checks, this PR includes Checkstyle linter. MD lint to follow in next PR

### CODE REVIEW

**Review by BFH-ktt1 — DISMISSED** [review]

**Review by BFH-ktt1 — DISMISSED** [review]

**Review by maehne — APPROVED** [review]
As using actually the pre-commit hooks seems to be optional, I am fine with this.

**Review by davidhutchens — APPROVED** [review]
I agree with @maehne that this is OK since it is optional for a developer. I like the idea of getting more instant feedback rather than waiting to see it in the PR.

My only question is: Is it fairly easy to ignore should the developer decide to do so? I ask this as I have seen several times when @MarcinOrlowski has reasonably asked to ignore something for a given PR to keep its size under control.

**Review by BFH-ktt1 — APPROVED** [review]

**Comment by MarcinOrlowski** [comment]
Yes, it is easy to disable given hook for on demand. I will update docs with examples how to do that.

**Comment by MarcinOrlowski** [comment]
Updated docs in #1170. 

* #1170

**Pull request merged**
