### PR TITLE
Fix the layout bugs of the component JHotkeyInput occurred in Linux platform and different look&feels

### PR DESCRIPTION
**Pull request by gtxzsxxk**
Sorry to disturbing you again. Recently I find that the look of the hotkey's input component is strange in the platform Linux, especially when we set to other look and feels. The height of the hotkey textarea is overflow in Linux. And it will get worse that we cannot see the red X mark again when we turn to the LookAndFeel GTK+. I find that the problems are give rise to the LookAndFeels and the platforms because when we change the lookandfeel, the gui's methods are overrided. And when we change the lookandfeel into the OS's theme (such as Windows, GTK+ and Mac OS X), the gui's methods are overrided again by the system and we can't even change them (in gtk+, setting the background color by `setBackground` has no effect). So this is too annoying.

To solve this, I make our height&width calculation policy more conservative and programmable. For example, You may note that the position of the text in the field sometimes will at the center vertically or a little bit downward. Sometimes the look seems good, sometimes they have some bias. That is over my control, but I have tried my best to keep them look the same, and now in Windows, Linux and Mac, their looks are acceptable with minor size differences.

### CODE REVIEW

**Review by davidhutchens — DISMISSED** [review]
Thank you for the followup. I can't check in Linux, but it still looks good in macOS. The code looks good.

**Comment by gtxzsxxk** [comment]
I must apologize for them, and I will keep testing it. Thanks for your patience.

**Comment by MarcinOrlowski** [comment]
While inputs look fine for me, the change introduces massive gap at the end of the list:

ss

**Review by MarcinOrlowski — CHANGES_REQUESTED** [review]
The massive gap at the bottom of both lists seems to be a side effect of these changes.

**Comment by gtxzsxxk** [comment]
Could you please do me a favor? Please go to the window tab and set the look and feel into the gtk+, restart, and send me a screenshot of the new look. This will help me assess the situation, thanks.

And let me explain the side effect. This is not a bug. Originally I added the gaps to avoid something being hidden by the gtk+ or other look and feels. After add this although sometimes the gap will happen, nothing will be blocked at least when we switch to different themes.

And I will try as requested if we could have a more elegant way to deal with the gtk+'s disorder.

**Comment by MarcinOrlowski** [comment]
Here is GTK+. Looks like the same problem is visible (the previous screenshot was from FlatLaf InteliJ):

Screenshot_20230820_140024

**Comment by gtxzsxxk** [comment]
@MarcinOrlowski thanks.

The problem is quite anooying, the behavior of the UI does not have any general common rules, which leads to the problem that we cannot see if this works good in all platforms. In my platform if i use gtk+, we can see some borders and we will find that the scroll bar is not that long to pull all the things out. 

Maybe i can use a dynamic way to detect whether the elements are blocked. If so, add blank lines. Otherwise we do nothing to provide a good layout. 

Let me do some work. Thanks for your patience.

**Comment by gtxzsxxk** [comment]
@MarcinOrlowski I thought I have solved the problem of the blank lines. I add them because sometimes the scroll panel's viewport will eat some hotkey bindings making them invisible. So I add them to pull them out and then they are visible. But after digging more, I found the origin of the eating bug.

`menuKeyPanel.setPreferredSize(menuKeyPanel.getSize());`

This is how I initialize the panel's height. It is incorrect and should be

```java
menuKeyPanel.setPreferredSize(new Dimension(menuKeyPanel.getSize().width,
            menuKeyPanel.getPreferredSize().height));
```

Now this fix works when I am testing on win mac and linux. Please check this.

**Comment by gtxzsxxk** [comment]
> Looks good to me. Though, I did just a quick test on Linux using FlatLaf IntelliJ look and feel. Though, I noticed the following unrelated to the original issue: The key names are printed in German despite the language chosen in Logisim-evolution is English (see screenshot below).

This is pretty strange. These texts come from the getKeyText and getModifiersExText methods. The two methods are trying to read the keycode's text from a property map. The name of the keys has a default in English. 

```java
public static String getKeyText(int keyCode) {
        if (keyCode >= VK_0 && keyCode <= VK_9 ||
            keyCode >= VK_A && keyCode <= VK_Z) {
            return String.valueOf((char)keyCode);
        }

        switch(keyCode) {
          case VK_ENTER: return Toolkit.getProperty("AWT.enter", "Enter");
          case VK_BACK_SPACE: return Toolkit.getProperty("AWT.backSpace", "Backspace");
          case VK_TAB: return Toolkit.getProperty("AWT.tab", "Tab");
          case VK_CANCEL: return Toolkit.getProperty("AWT.cancel", "Cancel");
          case VK_CLEAR: return Toolkit.getProperty("AWT.clear", "Clear");
          case VK_COMPOSE: return Toolkit.getProperty("AWT.compose", "Compose");
          case VK_PAUSE: return Toolkit.getProperty("AWT.pause", "Pause");
          case VK_CAPS_LOCK: return Toolkit.getProperty("AWT.capsLock", "Caps Lock");
          case VK_ESCAPE: return Toolkit.getProperty("AWT.escape", "Escape");
          case VK_SPACE: return Toolkit.getProperty("AWT.space", "Space");
          case VK_PAGE_UP: return Toolkit.getProperty("AWT.pgup", "Page Up");
          case VK_PAGE_DOWN: return Toolkit.getProperty("AWT.pgdn", "Page Down");
          case VK_END: return Toolkit.getProperty("AWT.end", "End");
```

But your image shows some German. According to the jdk documentation,

> public static [String](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html) getModifiersExText(int modifiers)
> Returns a String describing the extended modifier keys and mouse buttons, such as "Shift", "Button1", or "Ctrl+Shift". These strings can be localized by changing the awt.properties file.

So if the methods are not returning the default texts, it might indicate that your jdk are localized into German. This is pretty strange and let me spend some time digging that out.

**Comment by gtxzsxxk** [comment]
https://github.com/openjdk-mirror/jdk7u-jdk/tree/master/src/share/classes/sun/awt/resources

This is the localization of the awt.properties. It seems like it will return the value of the specified language. What is the language of your OS? Is that German? Do you mean I should make a fix so that the text the same as the locale specified in the logisim rather than the whole OS?

**Comment by maehne** [comment]
> https://github.com/openjdk-mirror/jdk7u-jdk/tree/master/src/share/classes/sun/awt/resources
> 
> This is the localization of the awt.properties. It seems like it will return the value of the specified language. What is the language of your OS? Is that German? Do you mean I should make a fix so that the text the same as the locale specified in the logisim rather than the whole OS?

Yes, my session locale is set to German. For me, the observed inconsistency is a minor issue. I would not spend extra effort to force consistency unless similar issues would pop up elsewhere.

**Comment by gtxzsxxk** [comment]
In all, it sounds interesting. I plan to have a try which may be in another PR to make it better.

**Comment by gtxzsxxk** [comment]
Well, I found the reason that why the names of the keys and modifiers are not localized. The methods `getModifiersExText` and `getKeyText` will load the properties from a resource which has been loaded with a system's default locale. Here are the code.

Toolkit.java
```java
try {
    resources = ResourceBundle.getBundle("sun.awt.resources.awt");
} catch (MissingResourceException e) {
    // No resource file; defaults will be used.
}
```

All names are hidden in the awt.properties. And note that this code is hard coded in the jdk's package, which will set the locale as the system's default, so we cannot assign logisim's locale into that, which gave rise to the problem that the hotkey bindings are not controlled by the international settings.

One way to fix that is that we can derive the Toolkit class and override the load method like this:

```java
resources = ResourceBundle.getBundle("sun.awt.resources.awt", ourLocale);
```

But it seems impossible because it will throw an error that unnamed module can't load sun.awt.resources.awt in module java.desktop. This is very hard to fix because it concerns some module-related problems and will mightly cause some unelegant changes and it led me into a XY problem.

So another way is that we directly copy the localized values from the jdk's source code into the logisim's strings. Kind of unelegant too.

Do you have any ideas?

**Comment by maehne** [comment]
Maybe @davidhutchens has a suggestion. My Java expertise is limited, as I am more familiar with C/C++.

**Comment by davidhutchens** [comment]
I have no special knowledge of the key names part of the Java/awt library. @gtxzsxxk seems to have researched it well. It therefore seems to me that the choices are:

1. Accept that the key names will be set by the OS language setting (@maehne's suggestion of not holding this PR over this issue).
2. Maintain our own key names in our locale files (@gtxzsxxk's suggestion of copying them into LE strings).

I lean toward 1 for this PR. We could create an issue if we wish to work on a PR for 2).

**Comment by gtxzsxxk** [comment]
> EDIT: Curious. I don't see this issue on my Mac where the keys are given by symbol rather than name.

Because the toolkit.java loads two resources. One is platform resources, which gives the symbol of the key, and another is the normal resources giving the readable key names like meta ctrl and so on. The platform resources have a higher priority so in macos the symbol will be displayed rather than the readable key name.

> Is it typical on other platforms to use names rather than symbols for the special keys? Or is it my English setting?

Yes, this will happen when using windows and linux. In mac it might not be a problem because all keys are symbols.

**Comment by davidhutchens** [comment]
Thank you for the explanation. If we adjust strings for locale, I would like to keep the key symbols where they exist. I still recommend not doing that in this PR.

@MarcinOrlowski: Have your concerns with this PR been addressed?

**Comment by gtxzsxxk** [comment]
I agree with @davidhutchens as well

**Comment by maehne** [comment]
@MarcinOrlowski: Any remarks from your side? Or can this be merged?

**Comment by MarcinOrlowski** [comment]
Sorry, for holding this up. Will do the tests of the updated PR in the morning.

**Comment by MarcinOrlowski** [comment]
LGTM, thanks.

**Review by MarcinOrlowski — APPROVED** [review]

**Pull request merged**
