### PR TITLE
Project logo

### PR DESCRIPTION
**Pull request by MarcinOrlowski**
* Added project logo
* Updated About dialog to show it (renders with Batik)
* Added logo to README
* Significantly reduced over-engineered  credits scroll code

### CODE REVIEW

**Comment by BFH-ktt1** [comment]
@MarcinOrlowski , I just tried after the merge, but unfortunately the logo is not correctly scaled in the about box on ubuntu 20.04LTS (did not jet check on windows and mac)
Screenshot from 2021-06-22 11-21-55

Could you look into it?

**Comment by MarcinOrlowski** [comment]
Sure, will check. But that's quite interesting given the fact the SVG canvas is given specific dimensions. Also works fine for me on `Ubuntu 20.04.2 LTS` (but that's Kubuntu, maybe that matters). In meantime. Can you (just in case) do clean rebuild (with `./gradlew clean`) and see?

**Comment by MarcinOrlowski** [comment]
I just noticed that fonts do not match the design. So I assume it made mistake not converting text into shapes and it now tries to render it. And you do not have fonts I used installed, so this is the result. Will fix that.

**Comment by MarcinOrlowski** [comment]
I opened #701 for me to not forget.

**Comment by MarcinOrlowski** [comment]
@BFH-ktt1 Please take a look at #704 and see if that fixes that issue for you.

**Pull request merged**
