### PR TITLE
Change mime-type in jpackage

### PR DESCRIPTION
**Pull request by juli-99**
Change the mime-type to be consistent between Flatpak and jpackage.
https://github.com/logisim-evolution/logisim-evolution/blob/a8e3c096bbdad57975bbe4e8731c1e6cf5d09023/support/Flatpak/com.github.reds.LogisimEvolution.xml#L1-L7

This also helps with the issues:
* #1471
* #1752

### CODE REVIEW

**Review by maehne — APPROVED** [review]
Thanks @juli-99 for the PR to provide consistency for the announced MIME type! It looks good to me!

**Review by MarcinOrlowski — APPROVED** [review]

**Comment by moekhalil** [comment]
For anyone on Windows who doesn't want to use nightly and needs this fixed asap w/o waiting for the next release, you can fix this issue by saving the registry modification code below into a file named `circ.reg` file and running it. 
 

<sub>(**Manual Instructions**: removing the registry MIME Content-Type key `application/octet-stream` should be all that's required, but I recommended making both changes by modifying the .circ class's `Content-Type` value and renaming the registry MIME Content-Type key `application/octet-stream` to `application/x-logisim-circuit`)</sub>
 



```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.circ]
"Content Type"="application/x-logisim-circuit"

[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\MIME\Database\Content Type\application/octet-stream]
"Extension"=".circ"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\MIME\Database\Content Type\application/x-logisim-circuit]
"Extension"=".circ"

```

**Comment by maehne** [comment]
@moekhalil: Thanks for describing this workaround. The nightly builds accumulate a lot of improvements / bug fixes from the past year and are in my experience comparable in reliability to the stable release. There have been (at least over the past year) no breaking changes to my knowledge (e.g. changes in the CIRC data format), which would affect users. You can expect a new stable release until beginning of October, as then we will start using Logisim-evolution with our new batch of 1st year EE students.

**Comment by moekhalil** [comment]
Np, just happy to help.

Thank you (and all other contributors) for contributing the support & time in making this app better, more accessible, and more stable for everyone.

Appreciate the heads up regarding nightly; I recently downloaded it, and so far so good! 

Looking forward to see what lies ahead for this project 😊

**Review by NoahRoters — COMMENTED** [review]
Changes definitely approved and pushed to boost it in the algorithm.  

Big thanks to [moekhalil](https://github.com/moekhalil) for the workaround:  
https://github.com/logisim-evolution/logisim-evolution/pull/1765#issuecomment-1699867177  

Works like a charm!

**Pull request merged**
